<?php

class RevcheckIgnore
{
    public static function ignore( $filename ) : bool
    {
        // Ignore dot files

        if ( $filename[0] == '.' )
            return true;

        // Ignore files other than xml assets

        if ( ( str_ends_with( $filename , '.xml' ) || str_ends_with( $filename , '.ent' ) ) == false )
            return true;

        // Ignore autogenerated files

        if ( str_starts_with( $filename , "entities." ) )
            return true;
        if ( str_contains( $filename , "/entities." ) )
            return true;
        if ( str_contains( $filename , "/versions.xml" ) )
            return true;

        // Only in English

        if ( $filename == "contributors.ent" )
            return true;
        if ( $filename == "contributors.xml" )
            return true;
        if ( $filename == "appendices/license.xml" )
            return true;
        if ( $filename == "appendices/license.xml" )
            return true;
        if ( $filename == "appendices/extensions.xml" )
            return true;
        if ( $filename == "appendices/reserved.constants.xml" )
            return true;
        if ( $filename == "reference/datetime/timezones.xml" )
            return true;
        if ( str_starts_with( $filename , 'chmonly/') )
            return true;
        if ( str_ends_with( $filename , '/book.developer.xml') )
            return true;

        // Only in translations

        if ( $filename == "translation.xml" )
            return true;

        // At least, do not ignore
        return false;
    }
}